### ISSUE TITLE
It fails to run react-native run-android with this dependency installed and doesn't work

### ISSUE THREAD

**Issue by Lyle-Rogers** [maitrungduc1410/react-native-loader-kit#13]
This is the main part of the error log after running react-native run-android: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.wang.avi:library:2.1.3.
     Searched in the following locations:
       - file:/C:/Users/adria/Desktop/My-Projects/Recipient Roads/Recipient_Roads_Frontend/node_modules/react-native/android/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - file:/C:/Users/adria/Desktop/My-Projects/Recipient Roads/Recipient_Roads_Frontend/node_modules/jsc-android/dist/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://repo.maven.apache.org/maven2/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://dl.google.com/dl/android/maven2/com/wang/avi/library/2.1.3/library-2.1.3.pom
       - https://www.jitpack.io/com/wang/avi/library/2.1.3/library-2.1.3.pom
     Required by:
         project :app > project :react-native-loader-kit

Thanks and please fix this issue.!.!.!.!

**Comment by airowe** [comment]
Having the same issue. @maitrungduc1410 Are you still maintaining?

@Lyle-Rogers Did you ever find a solution here?

**Comment by airowe** [comment]
Actually, found the fix [via this comment](https://github.com/HarlonWang/AVLoadingIndicatorView/issues/134#issuecomment-1306307542) on the root lib.

Update node_modules/react-native-loader-kit/android/build.gradle

and change the dependencies block on Line 59 to reference github instead of the broken maven link

`dependencies {
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.github.chenzj-king:AVLoadingIndicatorView:2.1.1'
}`

**Comment by airowe** [comment]
> Hi @airowe thanks for letting me know, I'll update the lib for this. So that you don't need to update from your end.
> 
> Get back to you soon

Happy to submit a pull request if that would make things easier.

**Comment by maitrungduc1410** [comment]
> > Hi @airowe thanks for letting me know, I'll update the lib for this. So that you don't need to update from your end.
> 
> > 
> 
> > Get back to you soon
> 
> 
> 
> Happy to submit a pull request if that would make things easier.

It'll be really great :)

**Comment by airowe** [comment]
> > > Hi @airowe thanks for letting me know, I'll update the lib for this. So that you don't need to update from your end.
> > 
> > 
> > > 
> > 
> > 
> > > Get back to you soon
> > 
> > 
> > Happy to submit a pull request if that would make things easier.
> 
> It'll be really great :)

I don't have repo rights. Only option is to fork the lib, which I'm willing to do.

**Comment by airowe** [comment]
https://github.com/maitrungduc1410/react-native-loader-kit/pull/32

**Comment by maitrungduc1410** [comment]
done with release 2.0.2

**Comment by maitrungduc1410** [comment]
`implementation 'com.github.chenzj-king:AVLoadingIndicatorView:2.1.1'` doesn't work any more, it's 404.

i have to publish to my own repo. Please upgrade to `react-native-loader-kit@2.0.5`
