### ISSUE TITLE
Android: Release apk is not assembling on RN 0.69.5.

### ISSUE THREAD

**Issue by ktarasenkowow** [maitrungduc1410/react-native-loader-kit#25]
Hi. I like your package but it dont assemble on rn 0.69.5. I hope you fix it ASAP =)

Platform: Android.
Type apk: release
react-native version: 0.69.5

Error logs:
> Task :react-native-loader-kit:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-loader-kit:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/username/.gradle/caches/transforms-3/202e7efeda83537a7bfc0441b98822fe/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 4 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

**Comment by maitrungduc1410** [comment]
Hi please upgrade to version `2.0.5`, It should be fine now. 

I tried to build release project with RN 0.72, fine for both ios and android

**Comment by iArchin** [comment]
I'm using RN 0.72.0 and I already using the latest version of the package which is 2.0.5 and I have the same problem: 

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-loader-kit:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:3: AAPT: error: resource android:color/system_neutral1_1000 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:4: AAPT: error: resource android:color/system_neutral1_900 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:5: AAPT: error: resource android:color/system_neutral1_0 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:6: AAPT: error: resource android:color/system_neutral1_800 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:7: AAPT: error: resource android:color/system_neutral1_700 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:8: AAPT: error: resource android:color/system_neutral1_600 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:9: AAPT: error: resource android:color/system_neutral1_500 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:10: AAPT: error: resource android:color/system_neutral1_400 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:11: AAPT: error: resource android:color/system_neutral1_300 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:12: AAPT: error: resource android:color/system_neutral1_200 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:13: AAPT: error: resource android:color/system_neutral1_100 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:14: AAPT: error: resource android:color/system_neutral1_50 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:15: AAPT: error: resource android:color/system_neutral1_10 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:16: AAPT: error: resource android:color/system_neutral2_1000 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:17: AAPT: error: resource android:color/system_neutral2_900 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:18: AAPT: error: resource android:color/system_neutral2_0 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:19: AAPT: error: resource android:color/system_neutral2_800 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:20: AAPT: error: resource android:color/system_neutral2_700 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:21: AAPT: error: resource android:color/system_neutral2_600 not found.
         
     ERROR:/home/ash/Desktop/MarcoApp/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:22: AAPT: error: resource android:color/system_neutral2_500 not found.`

**Comment by Ahmad-Elsayed** [comment]
why was this closed? the issue still exists

**Comment by maitrungduc1410** [comment]
@Ahmad-Elsayed okay let me check on it today and get back to you

**Comment by maitrungduc1410** [comment]
Hi @iArchin @Ahmad-Elsayed on which command are you guys facing this issue?

Just now I tested with these commands, they're all fine:
```
npx react-native build-android --mode=release
npm run android -- --mode="release"
```
My env (MacOS M2): 
```json
"react": "18.2.0",
"react-native": "0.74.0",
"react-native-loader-kit": "^2.0.8"
```

**Comment by maitrungduc1410** [comment]
maybe this can help you: https://github.com/yamill/react-native-orientation/issues/396#issuecomment-827265794

**Comment by maitrungduc1410** [comment]
a folk just fixed it: https://github.com/maitrungduc1410/react-native-loader-kit/issues/49

**Comment by Ahmad-Elsayed** [comment]
Thanks, I will try that.

**Comment by sberkeo** [comment]
thanks its worked.
