### ISSUE TITLE
SWIFT_VERSION not specified

### ISSUE THREAD

**Issue by MichaelTaylor3D** [maitrungduc1410/react-native-loader-kit#3]
I get the following error when running pod install

[!] Unable to determine Swift version for the following pods:
- `react-native-loader-kit` does not specify a Swift version and none of the targets (`Project`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by maitrungduc1410** [comment]
Will check and update you soon

**Comment by maitrungduc1410** [comment]
new version of the package has been released, please check.
