### ISSUE TITLE
Could not HEAD 'https://www.jitpack.io/com/github/chenzj-king/AVLoadingIndicatorView/2.1.1/AVLoadingIndicatorView-2.1.1.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by dingfeix** [maitrungduc1410/react-native-loader-kit#36]
Gradle: 8.0.1
AGPBI: {"kind":"warning","text":"Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.","sources":[{}]}

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-loader-kit:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-loader-kit:debugCompileClasspath'.
   > Could not resolve com.github.chenzj-king:AVLoadingIndicatorView:2.1.1.
     Required by:
         project :react-native-loader-kit
      > Could not resolve com.github.chenzj-king:AVLoadingIndicatorView:2.1.1.
         > Could not get resource 'https://www.jitpack.io/com/github/chenzj-king/AVLoadingIndicatorView/2.1.1/AVLoadingIndicatorView-2.1.1.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/chenzj-king/AVLoadingIndicatorView/2.1.1/AVLoadingIndicatorView-2.1.1.pom'. Received status code 403 from server: Forbidden

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by maitrungduc1410** [comment]
Lemme check and get back to u

**Comment by maitrungduc1410** [comment]
Hi Please upgrade to version `2.0.5`, I fixed this issue
