### ISSUE TITLE
the package "react-native-loader-kit" doesn't seem to be linked

### ISSUE THREAD

**Issue by rahuldasgupta** [maitrungduc1410/react-native-loader-kit#38]
On installing `"react-native-loader-kit": "^2.0.5"` on Expo SDK 48, getting the error on Expo Go

```
the package "react-native-loader-kit" doesn't seem to be linked. Make sure:
- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

**Dependencies**
```
"react-native-loader-kit": "^2.0.5",
"react": "18.2.0",
"react-native": "0.71.8",
"expo": "48.0.0"
```

Tried restarting the expo, even cleared cache with `npx expo start --clear`

**Comment by maitrungduc1410** [comment]
Lemme check on this and get back to you

**Comment by maitrungduc1410** [comment]
Hi @rahuldasgupta , I think it's not possible to use React native CLI library in Expo project unless you do `eject` from expo project.

Check here: https://help.daily.co/en/articles/4620485-can-i-use-daily-s-react-native-library-in-my-expo-project
