### ISSUE TITLE
compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by RuslanAugust** [maitrungduc1410/react-native-loader-kit#39]
Hi! Has anyone encountered this? It works fine on iOS, but on the Android emulator it gives an error when starting.

Execution failed for task ':tasks'.
> Could not create task ':react-native-loader-kit:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

System:
  OS: macOS 12.4
  CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Memory: 244.80 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.16.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.2
      - iOS 15.2
      - macOS 12.1
      - tvOS 15.2
      - watchOS 8.3
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 13.2.1/13C100
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/ruslan/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by maitrungduc1410** [comment]
as the error says: you need to set `compileSdkVersion` to 30 or later

It's in `android/build.gradle`

**Comment by RuslanAugust** [comment]
ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }

https://stackoverflow.com/questions/76644279/in-order-to-compile-java-9-source-please-set-compilesdkversion-to-30-or-above

I tried this solution, inserted this code and it worked)
subprojects { subproject ->
        afterEvaluate{
            if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
                android {
                    compileSdkVersion rootProject.ext.compileSdkVersion
                    buildToolsVersion rootProject.ext.buildToolsVersion
                }
            }
        }
    }

**Comment by xerdnew** [comment]
I was also experiencing this issue @RuslanAugust even though it was specified in build.gradle. Your solution worked but however it still failed with

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.72.5] `

Solved this by adding the following inside build.gradle as a tempory solution until fixed.
`LoaderKit_minSdkVersion = 21`
