### ISSUE TITLE
When building Android in React Native 0.73, I get error

### ISSUE THREAD

**Issue by LukakHR** [maitrungduc1410/react-native-loader-kit#46]
After upgrading to RN 0.73, I keep getting this error when building for Android:

```
/node_modules/react-native-loader-kit/android/src/main/java/com/reactnativeloaderkit/LoaderKitViewManager.java:24: error: cannot find symbol
    AVLoadingIndicatorView avi = new AVLoadingIndicatorView(context, null, R.style.AVLoadingIndicatorView);
      symbol:   variable style
  location: class R
```
  
  My package.json:
    "react-native": "^0.73.4",
    "react-native-loader-kit": "^2.0.5",

**Comment by LukakHR** [comment]
<img width="877" alt="Screenshot 2024-02-13 at 01 49 36" src="https://github.com/maitrungduc1410/react-native-loader-kit/assets/61033257/9128b443-d312-450f-9524-e3143ecf5563">

**Comment by maitrungduc1410** [comment]
Let me check on RN 0.73 and get back to you

**Comment by maitrungduc1410** [comment]
hi @LukakHR please upgrade to `2.0.7` and try again

**Comment by LukakHR** [comment]
Seems to be fine now, thank you
