### ISSUE TITLE
Error react-native-loader-kit:verifyReleaseResources

### ISSUE THREAD

**Issue by GonzaArts** [maitrungduc1410/react-native-loader-kit#49]
I am trying to copy the APK and I get an error from your project which is as follows:

```
> Task :react-native-loader-kit:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-loader-kit:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
```
   
   
   I have tried to change the build.gradle configuration but it still fails

**Comment by DarkShtir** [comment]
Same issue

**Comment by maitrungduc1410** [comment]
@DarkShtir which version of RN are you using?

**Comment by DarkShtir** [comment]
RN 0.73.7, and last version of  react-native-loader-kit

**Comment by maitrungduc1410** [comment]
hi @GonzaArts @DarkShtir on which command are you guys facing this issue?

Just now I tested with these commands, they're all fine:
```
npx react-native build-android --mode=release
npm run android -- --mode="release"
```
My env (MacOS M2): 
```json
"react": "18.2.0",
"react-native": "0.74.0",
"react-native-loader-kit": "^2.0.8"
```

**Comment by maitrungduc1410** [comment]
maybe this can help you: https://github.com/yamill/react-native-orientation/issues/396#issuecomment-827265794

**Comment by DarkShtir** [comment]
I'm using fastlane to create builds, and under hood fastlane is using `./gradlew assembleRelease -p` command

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-loader-kit/android/build.gradle b/node_modules/react-native-loader-kit/android/build.gradle
index d94248d..fed1ef9 100644
--- a/node_modules/react-native-loader-kit/android/build.gradle
+++ b/node_modules/react-native-loader-kit/android/build.gradle
@@ -18,10 +18,10 @@ def safeExtGet(prop, fallback) {
 }
 
 android {
-    compileSdkVersion safeExtGet('LoaderKit_compileSdkVersion', 30)
+    compileSdkVersion safeExtGet('LoaderKit_compileSdkVersion', 34)
     defaultConfig {
-        minSdkVersion safeExtGet('LoaderKit_minSdkVersion', 16)
-        targetSdkVersion safeExtGet('LoaderKit_targetSdkVersion', 30)
+        minSdkVersion safeExtGet('LoaderKit_minSdkVersion', 26)
+        targetSdkVersion safeExtGet('LoaderKit_targetSdkVersion', 34)
         versionCode 1
         versionName "1.0"

```
Thanks [maitrungduc1410](https://github.com/maitrungduc1410) to link

**Comment by maitrungduc1410** [comment]
if sdk version is the problem, you can override it in your `android/build.gradle` > `buildscript` > `ext`
```gradle
buildscript {
    ext {
        LoaderKit_compileSdkVersion = 34
        LoaderKit_minSdkVersion = 26
        LoaderKit_targetSdkVersion = 34
    }
```

**Comment by DarkShtir** [comment]
Thanks, this is great solution and it's working!
Maybe be useful add this information to troubleshooting article

**Comment by maitrungduc1410** [comment]
Great, I'm gonna add a troubleshoot section in readme

**Comment by GonzaArts** [comment]
Reviewing everything I have already tried it and it worked for me too. 

Thanks @maitrungduc1410 @DarkShtir
