### ISSUE TITLE
Detox build error

### ISSUE THREAD

**Issue by konstantinbylbas** [maitrungduc1410/react-native-loader-kit#50]
Received an error during detox build:

* What went wrong:
Execution failed for task ':react-native-loader-kit:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.73.6] C:\Users\Valerii\.gradle\caches\transforms-3\f9bfc26d83adad8b30da87d83b6c2021\transformed\jetified-react-android-0.73.6-debug\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)

<br>

Temporarily solved the problem by changing node_modules/react-native-loader-kit/android/build.gradle file:
- **compileSdkVersion safeExtGet('LoaderKit_compileSdkVersion', 30)** to **compileSdkVersion safeExtGet('LoaderKit_compileSdkVersion', 33)**;
- **minSdkVersion safeExtGet('LoaderKit_minSdkVersion', 16)** to **minSdkVersion safeExtGet('LoaderKit_minSdkVersion', 21)**;
- **targetSdkVersion safeExtGet('LoaderKit_targetSdkVersion', 30)** to **targetSdkVersion safeExtGet('LoaderKit_targetSdkVersion', 33)**.

**Comment by maitrungduc1410** [comment]
hi, for this issue, you can override sdk version. 

please check my comment: https://github.com/maitrungduc1410/react-native-loader-kit/issues/49#issuecomment-2090004480

**Comment by konstantinbylbas** [comment]
> hi, for this issue, you can override sdk version.
> 
> please check my comment: [#49 (comment)](https://github.com/maitrungduc1410/react-native-loader-kit/issues/49#issuecomment-2090004480)

Yeah. It fixed. Thanks!
