### ISSUE TITLE
Failded Build React Native CLI 0.74.3

### ISSUE THREAD

**Issue by featlast** [maitrungduc1410/react-native-loader-kit#51]
Greetings community, I was reviewing previous forums and they recommended downgrading, I already tried version 2.0.5 and 2.0.8 and it still fails, I also modified the android/buildgradle version and the release still does not compile
![image](https://github.com/user-attachments/assets/9101ef4e-7cc3-478c-90fe-3f3f2fe44c53)
![image](https://github.com/user-attachments/assets/7cb53b17-85c3-4c4f-81b0-15927503941d)

**Comment by maitrungduc1410** [comment]
let me try and get back to you

**Comment by thomaskyr** [comment]
Hello!
I think I have the same issue (**react-native 0.72.6**, having tried both with **react-native-loader-kit version 2.0.5** and **2.0.8**).
When I rebuild my project in Android studio, I have the following error:

**> Task :react-native-loader-kit:processDebugAndroidTestManifest FAILED**

uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.72.6] myapp/android/caches/transforms-3/bcf34badc8c43aa40690cad2eb0a7fd2/transformed/jetified-react-android-0.72.6-debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)


Issue persists even after invalidating caches -> cleaning project -> rebuilding project
The project gets rebuilt only when I remove react-native-loader-kit

**Comment by maitrungduc1410** [comment]
@thomaskyr that minsdk version please check my comment: https://github.com/maitrungduc1410/react-native-loader-kit/issues/49#issuecomment-2090004480

**Comment by maitrungduc1410** [comment]
@featlast I tried on latest version of RN, it's fine.

can you please screenshot (or copy) full error log?

**Comment by thomaskyr** [comment]
> @thomaskyr that minsdk version please check my comment: [#49 (comment)](https://github.com/maitrungduc1410/react-native-loader-kit/issues/49#issuecomment-2090004480)

Thanks, that indeed fixed it (minSdkVersion needs to be at most the same with my project's, other than that all good).

**Comment by hariskhalid366** [comment]
Having these error while build android apk
What went wrong:
Execution failed for task ':react-native-loader-kit:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /home/haris/Desktop/react-native/MusicPlayer/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:3: AAPT: error: resource android:color/system_neutral1_1000 not found.
         
     ERROR: /home/haris/Desktop/react-native/MusicPlayer/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:4: AAPT: error: resource android:color/system_neutral1_900 not found.
         
     ERROR: /home/haris/Desktop/react-native/MusicPlayer/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:5: AAPT: error: resource android:color/system_neutral1_0 not found.
         
     ERROR: /home/haris/Desktop/react-native/MusicPlayer/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:6: AAPT: error: resource android:color/system_neutral1_800 not found.

**Comment by maitrungduc1410** [comment]
hi @hariskhalid366 are you building for release? or dev?

what's your RN version?
