### ISSUE TITLE
Failed to create Release apk in React Native 0.72.4

### ISSUE THREAD

**Issue by narindere261** [maitrungduc1410/react-native-loader-kit#53]
* What went wrong:
Execution failed for task ':react-native-loader-kit:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/fws/Desktop/Projects/IPB/node_modules/react-native-loader-kit/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:3: AAPT: error: resource android:color/system_neutral1_1000 not found.

**Comment by maitrungduc1410** [comment]
please check these:
https://github.com/maitrungduc1410/react-native-loader-kit/issues/49
https://github.com/maitrungduc1410/react-native-loader-kit/issues/25

**Comment by narindere261** [comment]
Thank you for your prompt response, @maitrungduc1410
